package org.example.risabackend.user;

import org.example.risabackend.user.dto.UserResponseDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Set;

//@CrossOrigin(origins = "http://localhost:8081")
@RestController
@RequestMapping("/api/user") // ensures HTTP requests to /api/user is mapped to this controller class
public class UserController {

    private final UserService userService;

    @Autowired // Autowired -> means get the bean called userRepository which is auto-generated by Spring which we will use to handle the data
    public UserController(UserService userService) {
        this.userService = userService;
    }

    // GET
    @GetMapping
    public ResponseEntity<List<UserResponseDto>> getAllUsers() {
        List<UserResponseDto> userRequestDtos = userService.getAllUsers();
        return ResponseEntity.ok(userRequestDtos);
    }

    @GetMapping("id/{id}")
    public ResponseEntity<UserResponseDto> getUserById(@PathVariable Long id) {
        UserResponseDto user = userService.getUserDtoById(id);
        return ResponseEntity.ok(user);
    }

    @GetMapping("/phoneNumber/{phoneNumber}")
    public ResponseEntity<UserResponseDto> getUserByPhoneNumber(@PathVariable String phoneNumber) {
        UserResponseDto user = userService.getUserByPhoneNumber(phoneNumber);
        if (user == null) {
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        System.out.println(user.toString());
        return ResponseEntity.status(HttpStatus.OK).body(user);
    }

    // POST
    @PostMapping("/login")
    @ResponseBody // @ResponseBody ->  tells controller that returned object is automatically serialized into JSON and passed back into *HttpResponse* object
    ResponseEntity<UserResponseDto> loginUser(@RequestBody User newUser) {
        UserResponseDto userResponseDto = userService.getUserByPhoneNumber(newUser.getPhoneNumber());
        if (userResponseDto == null) {
            System.out.println("LOGIN: user does not exist");
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        // return ResponseEntity.ok(HttpStatus.CREATED).body();
        System.out.println("login: user exists");
        return ResponseEntity.status(HttpStatus.OK).body(userResponseDto);
//        return ResponseEntity.ok(Optional.of(userResponseDto));
    }

    @PostMapping("/register")
    @ResponseBody// @ResponseBody ->  tells controller that returned object is automatically serialized into JSON and passed back into *HttpResponse* object
    ResponseEntity<UserResponseDto> registerUser(@RequestBody User newUser) {
        UserResponseDto userResponseDto = userService.createUser(newUser);

        if (userResponseDto == null) {
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        // return ResponseEntity.ok(HttpStatus.CREATED).body();
        return ResponseEntity.status(HttpStatus.CREATED).body(userResponseDto);
    }

    @PostMapping("/newChatLog/{chatLogId}")
    void createNewChatLog(@PathVariable Long chatLogId, @RequestBody Set<Long> userIds) {
        userService.createNewChatLog(userIds, chatLogId);
//        return new ResponseEntity<>(userResponseDtos, HttpStatus.CREATED);
//        return ResponseEntity.ok(userService.createNewChatLog(userIds, chatLogId));
    }

//    @PostMapping("/sendNotification/{id}")
//    @ResponseBody
//    String sendNotification(@PathVariable String id, @RequestBody Notification notification) {
//        User getUser = getUserById(id);
//        try {
//            getUser.getNotifications().add(notification);
//            return "true";
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//    }

    // PUT

//    @PutMapping("/{id}")
//    User replaceUser(@RequestBody User newUser, @PathVariable Long id) {
//        return userRepository.findById(id)
//                .map(u -> {
//                    u.setFullName(newUser.getFullName());
//                    u.setEmail(newUser.getEmail());
//                    return userRepository.save(u);
//                })
//                .orElseGet(() -> userRepository.save(newUser));
//    }
//
//
//    // DELETE
//    @DeleteMapping("/{id}")
//    void deleteUser(@PathVariable Long id) {
//        userRepository.deleteById(id);
//    }
//
    @DeleteMapping("/deleteAll")
    void deleteAllUsers() {
        userService.deleteAllUsers();
    }
}