package org.example.risabackend.api.controllers;

import org.example.risabackend.api.dto.UserResponseDto;
import org.example.risabackend.persistence.entity.ChatLog;
import org.example.risabackend.persistence.entity.User;
import org.example.risabackend.persistence.repositories.ChatLogRepository;
import org.example.risabackend.persistence.repositories.UserRepository;
import org.example.risabackend.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

//@CrossOrigin(origins = "http://localhost:8081")
@RestController
@RequestMapping("/user") // ensures HTTP requests to /user is mapped to this controller class
public class UserController {

    private final UserService userService;
    private final UserRepository userRepository;
    private final ChatLogRepository chatLogRepository;

    @Autowired // Autowired -> means get the bean called userRepository which is auto-generated by Spring which we will use to handle the data
    public UserController(UserService userService, UserRepository userRepository, ChatLogRepository chatLogRepository) {
        this.userService = userService;
        this.userRepository = userRepository;
        this.chatLogRepository = chatLogRepository;
    }

    // GET

    @GetMapping
    public ResponseEntity<List<UserResponseDto>> getAllUsers() {
        List<UserResponseDto> userRequestDtos = userService.getAllUsers();
        return ResponseEntity.ok(userRequestDtos);
    }

    @GetMapping("id/{id}")
    public ResponseEntity<UserResponseDto> getUserById(@PathVariable Long id) {
        UserResponseDto userRequestDto = userService.getUseDtoById(id);
        return ResponseEntity.ok(userRequestDto);
    }

    @GetMapping("email/{email}")
    public ResponseEntity<UserResponseDto> getUserByEmail(@PathVariable String email) {
        UserResponseDto userRequestDto = userService.getUserByEmail(email);
        return ResponseEntity.ok(userRequestDto);
    }

//    @GetMapping("/userNotifications/{id}")
//    @ResponseBody
//    List<Notification> getUserNotifications(@PathVariable String id) {
//        User getUser = getUserById(id);
//        return getUser.getNotifications();
//    }

    // POST

    @PostMapping("/register")
    @ResponseBody // @ResponseBody ->  tells controller that returned object is automatically serialized into JSON and passed back into *HttpResponse* object
    ResponseEntity<Optional<UserResponseDto>> createUser(@RequestBody User newUser) {
        return ResponseEntity.ok(Optional.ofNullable(userService.createUser(newUser)));
    }

    @PostMapping("/newChatLog")
    @ResponseBody
    Set<User> createNewChatLog(@RequestBody Set<Long> userIds) {
        return userService.createNewChatLog(userIds);
    }

//    @PostMapping("/sendNotification/{id}")
//    @ResponseBody
//    String sendNotification(@PathVariable String id, @RequestBody Notification notification) {
//        User getUser = getUserById(id);
//        try {
//            getUser.getNotifications().add(notification);
//            return "true";
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//    }

    // PUT

//    @PutMapping("/{id}")
//    User replaceUser(@RequestBody User newUser, @PathVariable Long id) {
//        return userRepository.findById(id)
//                .map(u -> {
//                    u.setFullName(newUser.getFullName());
//                    u.setEmail(newUser.getEmail());
//                    return userRepository.save(u);
//                })
//                .orElseGet(() -> userRepository.save(newUser));
//    }
//
//
//    // DELETE
//    @DeleteMapping("/{id}")
//    void deleteUser(@PathVariable Long id) {
//        userRepository.deleteById(id);
//    }
//
    @DeleteMapping
    void deleteAllUsers() {
        userService.deleteAllUsers();
    }
}