package org.example.risabackend.api.controllers;

import org.example.risabackend.api.dto.UserResponseDto;
import org.example.risabackend.persistence.entity.User;
import org.example.risabackend.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.Set;

//@CrossOrigin(origins = "http://localhost:8081")
@RestController
@RequestMapping("/api/user") // ensures HTTP requests to /user is mapped to this controller class
public class UserController {

    private final UserService userService;

    @Autowired // Autowired -> means get the bean called userRepository which is auto-generated by Spring which we will use to handle the data
    public UserController(UserService userService) {
        this.userService = userService;
    }

    // GET
    @GetMapping
    public ResponseEntity<List<UserResponseDto>> getAllUsers() {
        List<UserResponseDto> userRequestDtos = userService.getAllUsers();
        return ResponseEntity.ok(userRequestDtos);
    }

    @GetMapping("id/{id}")
    public ResponseEntity<UserResponseDto> getUserById(@PathVariable Long id) {
        UserResponseDto user = userService.getUseDtoById(id);
        return ResponseEntity.ok(user);
    }

    @GetMapping("email/{email}")
    public ResponseEntity<UserResponseDto> getUserByEmail(@PathVariable String email) {
        UserResponseDto userRequestDto = userService.getUserByEmail(email);
        return ResponseEntity.ok(userRequestDto);
    }

    // POST
    @PostMapping("/login")
    @ResponseBody // @ResponseBody ->  tells controller that returned object is automatically serialized into JSON and passed back into *HttpResponse* object
    ResponseEntity<Optional<UserResponseDto>> loginUser(@RequestBody User newUser) {
        UserResponseDto userResponseDto = userService.getUserByEmail(newUser.getEmail());
        if (userResponseDto == null) {
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        // return ResponseEntity.ok(HttpStatus.CREATED).body();
        return ResponseEntity.ok(Optional.of(userResponseDto));
    }

    @PostMapping("/register")
    @ResponseBody // @ResponseBody ->  tells controller that returned object is automatically serialized into JSON and passed back into *HttpResponse* object
    ResponseEntity<Optional<UserResponseDto>> registerUser(@RequestBody User newUser) {
        UserResponseDto userResponseDto = userService.createUser(newUser);

        if (userResponseDto == null) {
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
        // return ResponseEntity.ok(HttpStatus.CREATED).body();
        return ResponseEntity.ok(Optional.of(userResponseDto));
    }

    @PostMapping("/newChatLog/{chatLogId}")
    void createNewChatLog(@PathVariable Long chatLogId, @RequestBody Set<Long> userIds) {
        userService.createNewChatLog(userIds, chatLogId);
//        return new ResponseEntity<>(userResponseDtos, HttpStatus.CREATED);
//        return ResponseEntity.ok(userService.createNewChatLog(userIds, chatLogId));
    }

//    @PostMapping("/sendNotification/{id}")
//    @ResponseBody
//    String sendNotification(@PathVariable String id, @RequestBody Notification notification) {
//        User getUser = getUserById(id);
//        try {
//            getUser.getNotifications().add(notification);
//            return "true";
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//    }

    // PUT

//    @PutMapping("/{id}")
//    User replaceUser(@RequestBody User newUser, @PathVariable Long id) {
//        return userRepository.findById(id)
//                .map(u -> {
//                    u.setFullName(newUser.getFullName());
//                    u.setEmail(newUser.getEmail());
//                    return userRepository.save(u);
//                })
//                .orElseGet(() -> userRepository.save(newUser));
//    }
//
//
//    // DELETE
//    @DeleteMapping("/{id}")
//    void deleteUser(@PathVariable Long id) {
//        userRepository.deleteById(id);
//    }
//
    @DeleteMapping
    void deleteAllUsers() {
        userService.deleteAllUsers();
    }
}